services:
  - type: web
    name: typeblitz-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
